networks:
  spm-net:
    driver: bridge
    name: spm-net

# volumes:
#   rabbitmq_data:
#     name: rabbitmq_data

services:
  # Frontend
  frontend:
    build: ./frontend
    image: spm/frontend:1.0
    container_name: spm-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - spm-net
  
  # Documentation
  swagger:
    build: 
      context: ./documentation
      dockerfile: Dockerfile
    image: spm/swagger:1.0
    container_name: spm-swagger
    restart: always
    ports:
      - "6008:6008"
    volumes:
      - ./swagger:/usr/src/app/swagger
    networks:
      - spm-net
