networks:
  spm-net:
    driver: bridge
    name: spm-net

volumes:
  user_db_data:

services:
# PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5434:80"
    depends_on:
      - user_db

  # Frontend
  frontend:
    build: ./frontend
    image: spm/frontend:1.0
    container_name: spm-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - spm-net
  
  # Documentation
  swagger:
    build: 
      context: ./documentation
      dockerfile: Dockerfile
    image: spm/swagger:1.0
    container_name: spm-swagger
    restart: always
    ports:
      - "6008:6008"
    volumes:
      - ./swagger:/usr/src/app/swagger
    networks:
      - spm-net

  # Backend
  user_service:
    build: ./backend/user_service
    image: spm/user_service:1.0
    container_name: spm_user_service
    restart: always
    networks:
      - spm-net
    ports:
      - "6000:6000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - user_db
    
  user_db:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - ./backend/user_service/db:/docker-entrypoint-initdb.d